In [33]:
'''Ejercicio 3.6.1.
Dado el documento, Esculturas_Parque_Arqueolgicos_Colombia.csv, cárgalo en un dataframe.'''

import pandas as pd

path = r'/Users/okashi/Desktop/Esculturas_Parque_Arqueolgicos_Colombia.csv'

df_esculturas = pd.read_csv(path, sep=',')

df_esculturas

,Parque Arqueologico,Elemento arqueológico,Nombre elemento arqueológico,Código ICANH,Descripción,Ubicación actual dentro del parque,Datos historicos,Dimensiones visibles,Técnica de elaboración,Datos bibliograficos
0,San Agustín,escultura,Figura masculina sin rostro,No. 380,Personaje sin rostro. Lleva tocado en la cabez...,Bosque de las estatuas,Se desconoce la ubicación de origen dentro del...,90cm x 43cm x 34 cm,"Talla poco trabajada, sin detalle de talla en ...","Sotomayor María Lucia, Uribe Maria Victoria. E..."
1,San Agustín,escultura,Figura masculina con una cara sobre el cuerpo,No. 24,Figura humana que tiene cubierta la cabeza co...,Bosque de las estatuas,Esta escultura se encontró en el montículo nor...,174cm x 70cm x 46 cm,"Talla en todos los costados, profunda, volúmen...","Sotomayor María Lucia, Uribe Maria Victoria. E..."
2,San Agustín,escultura,Figura con una serpiente,No. 40,"La cabeza es excesivamente grande, el cuerpo p...",Bosque de las estatuas,Procedente montículo sur de la mesita B. El p...,123 cm x 72cm x 45 cm.,Talla profunda. Formas naturalistas de muchos ...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
3,San Agustín,escultura,Guardián de tumba,No. 65,"Figura de rastros antropomorfos, ojos ovalados...",Bosque de las estatuas,Procedente del montículo norte mesita B. Según...,107 cm x 33cm x 26 cm,Talla poco profunda se trabaja con la forma de...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
4,San Agustín,escultura,Guardián de tumba,No. 70,"Figura de rastros antropomorfos, ojos ovalados...",Bosque de las estatuas,Procedente del montículo norte mesita B. Según...,67 cm x 38cm x 32 cm,Talla poco profunda se trabaja con la forma de...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
...,...,...,...,...,...,...,...,...,...,...
207,Ciudad Perdida,Anillo de terraza,Anillo de terraza,No. 189,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,Diámetro promedio 12m,El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
208,Ciudad Perdida,Muro de terraza,Muro de terraza,Muro 1. Unidad Visual 36,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,"Longitud del muro: 25,35 mts.",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
209,Ciudad Perdida,Muro de terraza,Muro de terraza,Muro 1. Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud del muro: 103,60 mts",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
210,Ciudad Perdida,Unidad Visual,Unidad visual,Unidad Visual 7,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,"Longitud aproximada de la unidad visual 407,...",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
211,Ciudad Perdida,Unidad Visual,Unidad visual,Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud aproximada de la unidad visual 302,...",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."

In [34]:
'''Ejercicio 3.6.2.
Muestra, los datos del registro cuyo índice es 105. ¿Cuál es el nombre del elemento buscado?'''

print(df_esculturas.iloc[105],'\n')
print('El índice 105 es:',df_esculturas.iloc[105]['Nombre elemento arqueológico'])

Parque Arqueologico                                                         San Agustín
Elemento arqueológico                                                         escultura
Nombre elemento arqueológico                              Personaje con collar y tocado
Código ICANH                                                                     No.179
Descripción                           Personaje con cara redondeada, ojos medianos a...
Ubicación actual dentro del parque                                   Museo arqueológico
Datos historicos                      Procede del sitio denominado El Tablón. “Poste...
Dimensiones visibles                                                 77cm x 44cm x 26cm
Técnica de elaboración                         Piedra tallada, de superficie homogénea.
Datos bibliograficos                  Sotomayor María Lucia, Uribe Maria Victoria. E...
Name: 105, dtype: object

El índice 105 es: Personaje con collar y tocado

In [35]:
'''Ejercicio 3.6.3.
Muestra el nombre y la ubicación de los registros cuyos índices son 24, 36, 125 y 182. 
¿Alguno de los elementos está en la misma ubicación?'''

df_esculturas.iloc[[24,36,125,182],[2,5]]

,Nombre elemento arqueológico,Ubicación actual dentro del parque
24,Columna en piedra con una cara en relieve,Bosque de las estatuas
36,Un mono con un niño.,Bosque de las estatuas
125,Figura con pescado en las manos,"Meseta A, Montículo VIII, Alto de los Idolos"
182,hipogeo,Alto del Duende

Los índices 24 y 36 tienen la misma ubicación.

In [36]:
'''Ejercicio 3.6.4.
Muestra el código ICANH de los registros con índices entre el 100 y 110'''

df_esculturas.iloc[100:111,[3]]

    Código ICANH
100       No 133
101       No.138
102      No 155A
103       No.168
104       No.173
105       No.179
106      No. 483
107       No.213
108       No.234
109       No.369
110        No.41

In [38]:
'''Ejercicio 3.6.5.
Utilizando el mismo dataframe, muestra solo los registros cuyo índice es impar. ¿Cuántas registros habría?'''

df_esculturas.iloc[lambda x: x.index % 2!= 0]

,Parque Arqueologico,Elemento arqueológico,Nombre elemento arqueológico,Código ICANH,Descripción,Ubicación actual dentro del parque,Datos historicos,Dimensiones visibles,Técnica de elaboración,Datos bibliograficos
1,San Agustín,escultura,Figura masculina con una cara sobre el cuerpo,No. 24,Figura humana que tiene cubierta la cabeza co...,Bosque de las estatuas,Esta escultura se encontró en el montículo nor...,174cm x 70cm x 46 cm,"Talla en todos los costados, profunda, volúmen...","Sotomayor María Lucia, Uribe Maria Victoria. E..."
3,San Agustín,escultura,Guardián de tumba,No. 65,"Figura de rastros antropomorfos, ojos ovalados...",Bosque de las estatuas,Procedente del montículo norte mesita B. Según...,107 cm x 33cm x 26 cm,Talla poco profunda se trabaja con la forma de...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
5,San Agustín,escultura,Guardián de tumba,No. 72,Figura de rostro antropomorfo; con ojos almend...,Bosque de las estatuas,Procedencia montículo norte. Mesita B. El arqu...,105cm x 40cm x 32 cm,Tallada poco profunda; se aprovecha la forma d...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
7,San Agustín,escultura,Guardián de tumba,No.75,"Representa una figura humana. Ojos cerrados, n...",Bosque de las estatuas,Procedencia montículo norte mesita B.,92cm x 60 cm x 17cm,"Talla poco profunda, inciso en la parte poster...","Sotomayor María Lucia, Uribe maria Victoria. E..."
9,San Agustín,escultura,Guardián de tumba,No. 93,"Figura de rastros antropomorfos, ojos ovalados...",Bosque de las estatuas,Procedente del montículo norte mesita B. Según...,49 cm x 40cm x 29 cm,Talla poco profunda se trabaja con la forma de...,"Sotomayor María Lucia, Uribe maria Victoria. E..."
...,...,...,...,...,...,...,...,...,...,...
203,Ciudad Perdida,Anillo de terraza,Anillo de terraza,No. 133,Anillo de terraza construifo a traves de hil...,El Canal,La historia del Parque Ciudad Perddia el cual ...,"Diámetro promedio 6,85m",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
205,Ciudad Perdida,Anillo de terraza,Anillo de terraza,No. 198,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,"Diámetro promedio 7,60m",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
207,Ciudad Perdida,Anillo de terraza,Anillo de terraza,No. 189,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,Diámetro promedio 12m,El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
209,Ciudad Perdida,Muro de terraza,Muro de terraza,Muro 1. Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud del muro: 103,60 mts",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
211,Ciudad Perdida,Unidad Visual,Unidad visual,Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud aproximada de la unidad visual 302,...",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."

In [43]:
'''Ejercicio 3.6.6.
Utilizando el mismo dataframe, muestra la ubicación actual de los registros cuyo índice tenga como valores 10, 20, 30, 40 y 50.'''

df_esculturas.iloc[[10,20,30,40,50],[5]]

   Ubicación actual dentro del parque
10             Bosque de las estatuas
20             Bosque de las estatuas
30             Bosque de las estatuas
40                           Mesita A
50    Montículo occidental.  Mesita A

In [163]:
'''Ejercicio 3.6.7.
Crea un nuevo dataframe basado en el anterior, pero cuyo índice sea Elemento arqueológico'''

df2 = df_esculturas.set_index('Elemento arqueológico')
df2

,Parque Arqueologico,Nombre elemento arqueológico,Código ICANH,Descripción,Ubicación actual dentro del parque,Datos historicos,Dimensiones visibles,Técnica de elaboración,Datos bibliograficos
Elemento arqueológico,,,,,,,,,
escultura,San Agustín,Figura masculina sin rostro,No. 380,Personaje sin rostro. Lleva tocado en la cabez...,Bosque de las estatuas,Se desconoce la ubicación de origen dentro del...,90cm x 43cm x 34 cm,"Talla poco trabajada, sin detalle de talla en ...","Sotomayor María Lucia, Uribe Maria Victoria. E..."
escultura,San Agustín,Figura masculina con una cara sobre el cuerpo,No. 24,Figura humana que tiene cubierta la cabeza co...,Bosque de las estatuas,Esta escultura se encontró en el montículo nor...,174cm x 70cm x 46 cm,"Talla en todos los costados, profunda, volúmen...","Sotomayor María Lucia, Uribe Maria Victoria. E..."
escultura,San Agustín,Figura con una serpiente,No. 40,"La cabeza es excesivamente grande, el cuerpo p...",Bosque de las estatuas,Procedente montículo sur de la mesita B. El p...,123 cm x 72cm x 45 cm.,Talla profunda. Formas naturalistas de muchos ...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
escultura,San Agustín,Guardián de tumba,No. 65,"Figura de rastros antropomorfos, ojos ovalados...",Bosque de las estatuas,Procedente del montículo norte mesita B. Según...,107 cm x 33cm x 26 cm,Talla poco profunda se trabaja con la forma de...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
escultura,San Agustín,Guardián de tumba,No. 70,"Figura de rastros antropomorfos, ojos ovalados...",Bosque de las estatuas,Procedente del montículo norte mesita B. Según...,67 cm x 38cm x 32 cm,Talla poco profunda se trabaja con la forma de...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
...,...,...,...,...,...,...,...,...,...
Anillo de terraza,Ciudad Perdida,Anillo de terraza,No. 189,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,Diámetro promedio 12m,El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Muro de terraza,Ciudad Perdida,Muro de terraza,Muro 1. Unidad Visual 36,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,"Longitud del muro: 25,35 mts.",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Muro de terraza,Ciudad Perdida,Muro de terraza,Muro 1. Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud del muro: 103,60 mts",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Unidad Visual,Ciudad Perdida,Unidad visual,Unidad Visual 7,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,"Longitud aproximada de la unidad visual 407,...",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Unidad Visual,Ciudad Perdida,Unidad visual,Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud aproximada de la unidad visual 302,...",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."

In [70]:
'''Ejercicio 3.6.8.
Del nuevo dataframe creado muestra todos los elementos que tienen un índice disto a escultura. ¿Cuántos elementos hay?'''

filtro1 = df2.loc[lambda x: x.index != 'escultura']


print('Número de elementos:',filtro1.shape[0])
filtro1

Número de elementos: 88

,Parque Arqueologico,Nombre elemento arqueológico,Código ICANH,Descripción,Ubicación actual dentro del parque,Datos historicos,Dimensiones visibles,Técnica de elaboración,Datos bibliograficos
Elemento arqueológico,,,,,,,,,
Sarcófago,San Agustín,Sarcófago,S-2,Sarcófago monolítico profundo de paredes relat...,Mesita B,Se desconoce su procedencia exacta dentro del ...,235cm x 73cm x 48cm.,Talla monolítica precisa,Pérez de Barradas José. Arqueología agustinian...
laja,San Agustín,Laja con representación de figura humana,No. 200,Representa una figura humana que lleva sus bra...,Bosque de las estatuas,"Esta laja encontrada junto con las número 199,...",130cm x 104 cm x 30cm,Figura poco elaborada y poco profunda. Volume...,"Sotomayor María Lucia, Uribe maria Victoria. E..."
laja,San Agustín,Laja con rostro antropomorfo,No.201,Laja con representación de un rostro antropomorfo,Bosque de las estatuas,Fue encontrada en el Batán (La Floresta); en 1...,97cm x 91cm x 24cm.,Técnica con relieve particularmente en la part...,"Sotomayor María Lucia, Uribe maria Victoria. E..."
laja,San Agustín,Relieve de una figura femenina que enseña un...,No. 202,La cabeza tiene forma de un arco de círculo c...,Bosque de las estatuas,Esta escultura se encontró al norte del sitio ...,90cm x 43cm x 34 cm,Talla La parte anterior presenta un trabajo de...,"Sotomayor María Lucia, Uribe Maria Victoria. E..."
estela,San Agustín,Chamán con pies hacia los lados,No. 203,Representa una figura humana.,Bosque de las estatuas,Según Uribe y Sotomayor esta laja fue encontr...,133cm X 98cm X 12 cm,"Talla poco profunda, inciso en la parte poster...",Gamboa Hinestrosa Pablo. La escultura en la so...
...,...,...,...,...,...,...,...,...,...
Anillo de terraza,Ciudad Perdida,Anillo de terraza,No. 189,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,Diámetro promedio 12m,El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Muro de terraza,Ciudad Perdida,Muro de terraza,Muro 1. Unidad Visual 36,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,"Longitud del muro: 25,35 mts.",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Muro de terraza,Ciudad Perdida,Muro de terraza,Muro 1. Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud del muro: 103,60 mts",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Unidad Visual,Ciudad Perdida,Unidad visual,Unidad Visual 7,Anillo de terraza construifo a traves de hil...,La Gallera,La historia del Parque Ciudad Perdida el cual ...,"Longitud aproximada de la unidad visual 407,...",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."
Unidad Visual,Ciudad Perdida,Unidad visual,Unidad Visual 36,Anillo de terraza construifo a traves de hil...,Piedras,La historia del Parque Ciudad Perdida el cual ...,"Longitud aproximada de la unidad visual 302,...",El sistema constructivo empleado es el de la t...,"CADAVID, C., Gilberto y HERRERA DE TURBAY, Lui..."

In [74]:
'''Ejercicio 3.6.9.
Del nuevo dataframe muestra todos los elementos cuyo índice es Sarcófago. ¿Cuántos elementos hay?'''

filtro2 = df2.loc[lambda x: x.index == 'Sarcófago']

print('Número de elementos:',filtro2.shape[0])
filtro2

Número de elementos: 5

,Parque Arqueologico,Nombre elemento arqueológico,Código ICANH,Descripción,Ubicación actual dentro del parque,Datos historicos,Dimensiones visibles,Técnica de elaboración,Datos bibliograficos
Elemento arqueológico,,,,,,,,,
Sarcófago,San Agustín,Sarcófago,S-2,Sarcófago monolítico profundo de paredes relat...,Mesita B,Se desconoce su procedencia exacta dentro del ...,235cm x 73cm x 48cm.,Talla monolítica precisa,Pérez de Barradas José. Arqueología agustinian...
Sarcófago,San Agustín,Sarcófago,S-1,Sarcófago monolítico con vertedera en la parte...,Mesita B,"Este sarcófago es, aparentemente, al que se re...",240cm x 70cm x 50cm.,talla precisa,Pérez de Barradas José. Arqueología agustinian...
Sarcófago,Alto de los Idolos,Sarcófago,S-3,Sarcófago monolítico con canal de desague,Montículo !. Meseta A. Alto de los Idolos,El sarcófago No.3 del Montículo 1. El primero ...,255cm x 73cm x 43cm.,Talla monolítica y precisa. Rastros de policro...,"Duque Gómez, Luis A., Cubillos, Julio Cesar. A..."
Sarcófago,Alto de los Idolos,Sarcófago monolítico con dos agarraderas.,S-4,"Sarcófago monolítico ancho, de paredes gruesas...",Montículo II. Meseta A. Alto de Los Ídolos,"Este sarcófago fue reconocido por Preuss, en 1...",300cm x 129cm x 70cm.,Talla monolítica realizada con precisión. Las ...,"Duque Gómez, Luis A., Cubillos, Julio Cesar. A..."
Sarcófago,Alto de los Idolos,Sarcófago monolítico con tapa y vertedera.,S-5,Sarcófago monolítico con vertedera y tapa sin ...,"Montículo VII. Meseta A, Alto de Los Ídolos.","Sobre este sarcófago se refiere Preuss, “Este ...",Sarcófago : 245cm x 48cm x 43cm. Tapa : 241c...,"Talla monolítica, sin decoración con rastros d...","Duque Gómez, Luis A., Cubillos, Julio Cesar. A..."

In [118]:
'''Ejercicio 3.6.10.
Convierte el resultado del ejercicio anterior en un nuevo dataframe, reinicia su índice y muestra el Parque Arqueologico de los 3 primeros elementos'''
import pandas

df3 = df2.loc[lambda x: x.index == 'Sarcófago'].copy()
df3 = df3.reset_index()
df3.iloc[0:3,[1]]

  Parque Arqueologico
0         San Agustín
1         San Agustín
2  Alto de los Idolos

In [121]:
'''Ejercicio 3.7.1.
Dado el documento, ejecucion-presupuestaria_Chile-febrero-2023.csv'''

import pandas as pd

path = r'/Users/okashi/Desktop/ejecucion-presupuestaria_Chile-febrero-2023.csv'

df_presupuestos = pd.read_csv(path, sep=';')

df_presupuestos

,Año,Mes,Moneda,Subtítulo,Nombre_Subtítulo,Ejecución_de_FEBRERO,Ejecución_a_FEBRERO
0,2023,Febrero,DOLARES,1,IMPUESTOS,15844,39642
1,2023,Febrero,DOLARES,6,RENTAS DE LA PROPIEDAD,27215,62850
2,2023,Febrero,DOLARES,7,INGRESOS DE OPERACIÓN,230,477
3,2023,Febrero,DOLARES,8,OTROS INGRESOS CORRIENTES,238527,239760
4,2023,Febrero,DOLARES,11,VENTA DE ACTIVOS FINANCIEROS,-388279,925253
5,2023,Febrero,DOLARES,12,RECUPERACIÓN DE PRÉSTAMOS,78,585
6,2023,Febrero,DOLARES,21,GASTOS EN PERSONAL,8703,17232
7,2023,Febrero,DOLARES,22,BIENES Y SERVICIOS DE CONSUMO,20441,25054
8,2023,Febrero,DOLARES,23,PRESTACIONES DE SEGURIDAD SOCIAL,7,7
9,2023,Febrero,DOLARES,24,TRANSFERENCIAS CORRIENTES,699,33176
10,2023,Febrero,DOLARES,25,INTEGROS AL FISCO,0,116
11,2023,Febrero,DOLARES,29,ADQUISICIÓN DE ACTIVOS NO FINANCIEROS,33,694
12,2023,Febrero,DOLARES,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,-188426,785800
13,2023,Febrero,DOLARES,31,INICIATIVAS DE INVERSIÓN,0,4
14,2023,Febrero,DOLARES,32,PRÉSTAMOS,35,359
15,2023,Febrero,DOLARES,34,SERVICIO DE LA DEUDA,36240,379109
16,2023,Febrero,PESOS,1,IMPUESTOS,4096501621,9534921798
17,2023,Febrero,PESOS,4,IMPOSICIONES PREVISIONALES,318948856,566922220
18,2023,Febrero,PESOS,5,TRANSFERENCIAS CORRIENTES,3637932,6310790
19,2023,Febrero,PESOS,6,RENTAS DE LA PROPIEDAD,26173541,1039601756
20,2023,Febrero,PESOS,7,INGRESOS DE OPERACIÓN,123453207,223880388
21,2023,Febrero,PESOS,8,OTROS INGRESOS CORRIENTES,303687056,558446654
22,2023,Febrero,PESOS,9,APORTE FISCAL,489240,489240
23,2023,Febrero,PESOS,10,VENTA DE ACTIVOS NO FINANCIEROS,3154117,3402595
24,2023,Febrero,PESOS,11,VENTA DE ACTIVOS FINANCIEROS,1349425712,1861934948
25,2023,Febrero,PESOS,12,RECUPERACIÓN DE PRÉSTAMOS,243365358,1088434258
26,2023,Febrero,PESOS,13,TRANSFERENCIAS PARA GASTOS DE CAPITAL,8536766,16164561
27,2023,Febrero,PESOS,14,ENDEUDAMIENTO,3442520900,3442520900
28,2023,Febrero,PESOS,21,GASTOS EN PERSONAL,1008082775,2095259467
29,2023,Febrero,PESOS,22,BIENES Y SERVICIOS DE CONSUMO,355559721,666083207
30,2023,Febrero,PESOS,23,PRESTACIONES DE SEGURIDAD SOCIAL,1119401177,2143056664
31,2023,Febrero,PESOS,24,TRANSFERENCIAS CORRIENTES,1853815070,3672236118
32,2023,Febrero,PESOS,25,INTEGROS AL FISCO,35168020,79620638
33,2023,Febrero,PESOS,26,OTROS GASTOS CORRIENTES,8037272,32781117
34,2023,Febrero,PESOS,27,APORTE FISCAL LIBRE,974050,22172356
35,2023,Febrero,PESOS,28,APORTE FISCAL PARA SERVICIO DE LA DEUDA,0,138641
36,2023,Febrero,PESOS,29,ADQUISICIÓN DE ACTIVOS NO FINANCIEROS,3180188,13422080
37,2023,Febrero,PESOS,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,4898793746,5741252185
38,2023,Febrero,PESOS,31,INICIATIVAS DE INVERSIÓN,88132496,88474644
39,2023,Febrero,PESOS,32,PRÉSTAMOS,91381738,152643300
40,2023,Febrero,PESOS,33,TRANSFERENCIAS DE CAPITAL,282609345,532807908
41,2023,Febrero,PESOS,34,SERVICIO DE LA DEUDA,816469672,2646331382

In [127]:
'''Ejercicio 3.7.2.
muestra las columnas Nombre_Subtítulo y Ejecución_de_FEBRERO'''

df_presupuestos[['Nombre_Subtítulo','Ejecución_de_FEBRERO']]

                           Nombre_Subtítulo  Ejecución_de_FEBRERO
0                                 IMPUESTOS                 15844
1                    RENTAS DE LA PROPIEDAD                 27215
2                     INGRESOS DE OPERACIÓN                   230
3                 OTROS INGRESOS CORRIENTES                238527
4              VENTA DE ACTIVOS FINANCIEROS               -388279
5                 RECUPERACIÓN DE PRÉSTAMOS                    78
6                        GASTOS EN PERSONAL                  8703
7             BIENES Y SERVICIOS DE CONSUMO                 20441
8          PRESTACIONES DE SEGURIDAD SOCIAL                     7
9                 TRANSFERENCIAS CORRIENTES                   699
10                        INTEGROS AL FISCO                     0
11    ADQUISICIÓN DE ACTIVOS NO FINANCIEROS                    33
12       ADQUISICIÓN DE ACTIVOS FINANCIEROS               -188426
13                 INICIATIVAS DE INVERSIÓN                     0
14                                PRÉSTAMOS                    35
15                     SERVICIO DE LA DEUDA                 36240
16                                IMPUESTOS            4096501621
17               IMPOSICIONES PREVISIONALES             318948856
18                TRANSFERENCIAS CORRIENTES               3637932
19                   RENTAS DE LA PROPIEDAD              26173541
20                    INGRESOS DE OPERACIÓN             123453207
21                OTROS INGRESOS CORRIENTES             303687056
22                            APORTE FISCAL                489240
23          VENTA DE ACTIVOS NO FINANCIEROS               3154117
24             VENTA DE ACTIVOS FINANCIEROS            1349425712
25                RECUPERACIÓN DE PRÉSTAMOS             243365358
26    TRANSFERENCIAS PARA GASTOS DE CAPITAL               8536766
27                            ENDEUDAMIENTO            3442520900
28                       GASTOS EN PERSONAL            1008082775
29            BIENES Y SERVICIOS DE CONSUMO             355559721
30         PRESTACIONES DE SEGURIDAD SOCIAL            1119401177
31                TRANSFERENCIAS CORRIENTES            1853815070
32                        INTEGROS AL FISCO              35168020
33                  OTROS GASTOS CORRIENTES               8037272
34                      APORTE FISCAL LIBRE                974050
35  APORTE FISCAL PARA SERVICIO DE LA DEUDA                     0
36    ADQUISICIÓN DE ACTIVOS NO FINANCIEROS               3180188
37       ADQUISICIÓN DE ACTIVOS FINANCIEROS            4898793746
38                 INICIATIVAS DE INVERSIÓN              88132496
39                                PRÉSTAMOS              91381738
40                TRANSFERENCIAS DE CAPITAL             282609345
41                     SERVICIO DE LA DEUDA             816469672

In [133]:
'''Ejercicio 3.7.3.
muestra los registros cuya ejecución de febrero haya sido menor o igual que 0. Utiliza un condicional simple para realizar la consulta'''

df_presupuestos[df_presupuestos['Ejecución_de_FEBRERO']<=0]

,Año,Mes,Moneda,Subtítulo,Nombre_Subtítulo,Ejecución_de_FEBRERO,Ejecución_a_FEBRERO
4,2023,Febrero,DOLARES,11,VENTA DE ACTIVOS FINANCIEROS,-388279,925253
10,2023,Febrero,DOLARES,25,INTEGROS AL FISCO,0,116
12,2023,Febrero,DOLARES,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,-188426,785800
13,2023,Febrero,DOLARES,31,INICIATIVAS DE INVERSIÓN,0,4
35,2023,Febrero,PESOS,28,APORTE FISCAL PARA SERVICIO DE LA DEUDA,0,138641

In [140]:
'''Ejercicio 3.7.4.
Realiza, de nuevo, la consulta del ejercicio 3.7.3 pero, esta vez, muestra solo el Nombre_Subtítulo y la Ejecución_de_FEBRERO'''

df_presupuestos.loc[df_presupuestos['Ejecución_de_FEBRERO']<=0,['Nombre_Subtítulo','Ejecución_de_FEBRERO']]

                           Nombre_Subtítulo  Ejecución_de_FEBRERO
4              VENTA DE ACTIVOS FINANCIEROS               -388279
10                        INTEGROS AL FISCO                     0
12       ADQUISICIÓN DE ACTIVOS FINANCIEROS               -188426
13                 INICIATIVAS DE INVERSIÓN                     0
35  APORTE FISCAL PARA SERVICIO DE LA DEUDA                     0

In [145]:
'''Ejercicio 3.7.5.
Utilizando el mismo dataframe, muestra los registros cuya ejecución de febrero sea mayor de 20000 DOLARES'''

df_presupuestos[(df_presupuestos['Ejecución_de_FEBRERO']>20000)&(df_presupuestos['Moneda']=='DOLARES')]

,Año,Mes,Moneda,Subtítulo,Nombre_Subtítulo,Ejecución_de_FEBRERO,Ejecución_a_FEBRERO
1,2023,Febrero,DOLARES,6,RENTAS DE LA PROPIEDAD,27215,62850
3,2023,Febrero,DOLARES,8,OTROS INGRESOS CORRIENTES,238527,239760
7,2023,Febrero,DOLARES,22,BIENES Y SERVICIOS DE CONSUMO,20441,25054
15,2023,Febrero,DOLARES,34,SERVICIO DE LA DEUDA,36240,379109

In [148]:
'''Ejercicio 3.7.6.
Muestra ahora, del mismo dataframe, los Subtítulos y la Ejecución_a_FEBRERO de los registros cuya ejecución a febrero haya sido mayor que 10000000 de PESOS.'''

df_presupuestos.loc[(df_presupuestos['Ejecución_a_FEBRERO']>10000000)&(df_presupuestos['Moneda']=='PESOS'),['Subtítulo','Ejecución_a_FEBRERO']]

    Subtítulo  Ejecución_a_FEBRERO
16          1           9534921798
17          4            566922220
19          6           1039601756
20          7            223880388
21          8            558446654
24         11           1861934948
25         12           1088434258
26         13             16164561
27         14           3442520900
28         21           2095259467
29         22            666083207
30         23           2143056664
31         24           3672236118
32         25             79620638
33         26             32781117
34         27             22172356
36         29             13422080
37         30           5741252185
38         31             88474644
39         32            152643300
40         33            532807908
41         34           2646331382

In [149]:
'''Ejercicio 3.7.7.
Dada la lista ["IMPUESTOS","RENTAS DE LA PROPIEDAD","INGRESOS DE OPERACIÓN","VENTA DE ACTIVOS FINANCIEROS"]
y utilizando el dataframe anterior, muestra los registros cuyo nombre de subtítulo coincida con alguno de los elementos de la lista'''


import pandas as pd

path = r'/Users/okashi/Desktop/ejecucion-presupuestaria_Chile-febrero-2023.csv'

df_presupuestos = pd.read_csv(path, sep=';')
lista = ["IMPUESTOS","RENTAS DE LA PROPIEDAD","INGRESOS DE OPERACIÓN","VENTA DE ACTIVOS FINANCIEROS"]

df_presupuestos.loc[df_presupuestos['Nombre_Subtítulo'].isin(lista)]

,Año,Mes,Moneda,Subtítulo,Nombre_Subtítulo,Ejecución_de_FEBRERO,Ejecución_a_FEBRERO
0,2023,Febrero,DOLARES,1,IMPUESTOS,15844,39642
1,2023,Febrero,DOLARES,6,RENTAS DE LA PROPIEDAD,27215,62850
2,2023,Febrero,DOLARES,7,INGRESOS DE OPERACIÓN,230,477
4,2023,Febrero,DOLARES,11,VENTA DE ACTIVOS FINANCIEROS,-388279,925253
16,2023,Febrero,PESOS,1,IMPUESTOS,4096501621,9534921798
19,2023,Febrero,PESOS,6,RENTAS DE LA PROPIEDAD,26173541,1039601756
20,2023,Febrero,PESOS,7,INGRESOS DE OPERACIÓN,123453207,223880388
24,2023,Febrero,PESOS,11,VENTA DE ACTIVOS FINANCIEROS,1349425712,1861934948

In [154]:
'''Ejercicio 3.7.8.
Muestra ahora solo los registros cuya ejecución de febrero sea mayor de 10000 DOLARES 
y cuyo nombre de subtítulo coincida con alguno de los elementos de la lista proporcionada en el ejercicio 3.7.7'''

lista = ["IMPUESTOS","RENTAS DE LA PROPIEDAD","INGRESOS DE OPERACIÓN","VENTA DE ACTIVOS FINANCIEROS"]

df_presupuestos.loc[(df_presupuestos['Ejecución_de_FEBRERO']>10000)&
                    (df_presupuestos['Nombre_Subtítulo'].isin(lista))
                    &(df_presupuestos['Moneda']=='DOLARES')]

,Año,Mes,Moneda,Subtítulo,Nombre_Subtítulo,Ejecución_de_FEBRERO,Ejecución_a_FEBRERO
0,2023,Febrero,DOLARES,1,IMPUESTOS,15844,39642
1,2023,Febrero,DOLARES,6,RENTAS DE LA PROPIEDAD,27215,62850

In [156]:
'''Ejercicio 3.7.9.
muestra los registros en los que la diferencia entre la Ejecución_a_FEBRERO menos la Ejecución_de_FEBRERO sea igual a 0'''

import pandas as pd

path = r'/Users/okashi/Desktop/ejecucion-presupuestaria_Chile-febrero-2023.csv'

df_presupuestos = pd.read_csv(path, sep=';')

df_presupuestos[df_presupuestos['Ejecución_a_FEBRERO']-df_presupuestos['Ejecución_de_FEBRERO']==0]

,Año,Mes,Moneda,Subtítulo,Nombre_Subtítulo,Ejecución_de_FEBRERO,Ejecución_a_FEBRERO
8,2023,Febrero,DOLARES,23,PRESTACIONES DE SEGURIDAD SOCIAL,7,7
22,2023,Febrero,PESOS,9,APORTE FISCAL,489240,489240
27,2023,Febrero,PESOS,14,ENDEUDAMIENTO,3442520900,3442520900

In [161]:
'''Ejercicio 3.7.10.
Muestra ahora los registros cuya diferencia entre la Ejecución_a_FEBRERO menos la Ejecución_de_FEBRERO sea mayor que 250000 DOLARES.'''

df_presupuestos[(df_presupuestos['Ejecución_a_FEBRERO']-df_presupuestos['Ejecución_de_FEBRERO']>250000)
                    & (df_presupuestos['Moneda']== 'DOLARES')]

,Año,Mes,Moneda,Subtítulo,Nombre_Subtítulo,Ejecución_de_FEBRERO,Ejecución_a_FEBRERO
4,2023,Febrero,DOLARES,11,VENTA DE ACTIVOS FINANCIEROS,-388279,925253
12,2023,Febrero,DOLARES,30,ADQUISICIÓN DE ACTIVOS FINANCIEROS,-188426,785800
15,2023,Febrero,DOLARES,34,SERVICIO DE LA DEUDA,36240,379109