In [1]:
#cargo datos
import pandas as pd
import csv

path = r'https://www.pilgrimsolutions.com/dataset/DatosVino2.csv'
df = pd.read_csv(path, sep=';')
df

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella
0,13606,0,0,"0,39","0,14","4,99","0,073","1,02195","5,9","0,12","6,6",B,5,?,1.0,"4,56"
1,3119,0,0,"2,19","2,58","5,54","0,205","0,95373","6,4","0,49",112,b,4,?,NaN,"3,01"
2,1190,0,0,"1,44","-1,54","5,1","0,058","0,99271","7,1","0,39","10,2",B,2,?,1.0,1
3,5261,0,0,"0,5","0,3","5,23","0,276","0,9959","3,5","-0,81","4,4",R,4,?,3.0,"1,85"
4,2871,0,0,"-0,1","0,3","5,75","0,048","1,02724","7,2","0,44","10,1",M,2,?,1.0,"1,28"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,"0,41","0,17","8,55","-0,079","0,96961","9,5","0,45","12,7",M,2,*,3.0,"1,55"
6361,4285,0,0,"-0,77","0,29","8,96","0,042","0,99304","8,9","0,47","10,3",B,2,?,1.0,"3,79"
6362,13580,0,0,"0,41","0,07","8,88","0,587","0,9962","4,8","3,72","7,6",M,3,?,2.0,"2,15"
6363,10080,0,0,"-0,2","0,38","8,19","0,052","1,00796","13,6","0,44","13,8",B,2,*,1.0,"2,44"
6364,216,0,0,"0,22","-0,6","8,22","0,316","0,99834","9,1","1,79","9,5",R,2,*,1.0,"6,18"

In [2]:
#informaciÃ³n
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6365 entries, 0 to 6364
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              6365 non-null   int64
 1   Beneficio       6365 non-null   int64
 2   Compra          6365 non-null   int64
 3   Acidez          6365 non-null   object
 4   AcidoCitrico    6365 non-null   object
 5   pH              6365 non-null   object
 6   CloruroSodico   6365 non-null   object
 7   Densidad        6365 non-null   object
 8   Azucar          6365 non-null   object
 9   Sulfatos        5761 non-null   object
 10  Alcohol         6365 non-null   object
 11  Etiqueta        6365 non-null   object
 12  CalifProductor  6365 non-null   int64
 13  Clasificacion   6365 non-null   object
 14  Region          6258 non-null   float64
 15  PrecioBotella   6365 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 795.8+ KB

In [3]:
#ver duplicados
df.duplicated().sum()

0

In [4]:
#ver nulos, realmente el porcentaje de nulos no es tan significativo, las columnas podrÃ­an ser eliminadas, pero decido mantenerlas.
df.isnull().sum()

ID                  0
Beneficio           0
Compra              0
Acidez              0
AcidoCitrico        0
pH                  0
CloruroSodico       0
Densidad            0
Azucar              0
Sulfatos          604
Alcohol             0
Etiqueta            0
CalifProductor      0
Clasificacion       0
Region            107
PrecioBotella       0
dtype: int64

In [5]:
#elimino los nulos de RegiÃ³n sustituyendolos por cero, en una nueva columna en una copia del dataframe
#en relaciÃ³n a los nulos contenidos en sulfatos decido sustituirlos por la mediana

df2 =df.copy()
df2['Region'] = df2['Region']
df2['Region'].fillna(0, inplace=True)

df2['Sulfatos'] = df2['Sulfatos'].str.replace(',', '.').astype(float)#me aseguro de que pase a numerico, quitando la coma y poniendo punto
df2['Sulfatos'] = pd.to_numeric(df2['Sulfatos'], errors='coerce')
median_sulfatos = df2['Sulfatos'].median()
df2['Sulfatos'] = df2['Sulfatos'].fillna(median_sulfatos)
df2

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella
0,13606,0,0,"0,39","0,14","4,99","0,073","1,02195","5,9",0.12,"6,6",B,5,?,1.0,"4,56"
1,3119,0,0,"2,19","2,58","5,54","0,205","0,95373","6,4",0.49,112,b,4,?,0.0,"3,01"
2,1190,0,0,"1,44","-1,54","5,1","0,058","0,99271","7,1",0.39,"10,2",B,2,?,1.0,1
3,5261,0,0,"0,5","0,3","5,23","0,276","0,9959","3,5",-0.81,"4,4",R,4,?,3.0,"1,85"
4,2871,0,0,"-0,1","0,3","5,75","0,048","1,02724","7,2",0.44,"10,1",M,2,?,1.0,"1,28"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,"0,41","0,17","8,55","-0,079","0,96961","9,5",0.45,"12,7",M,2,*,3.0,"1,55"
6361,4285,0,0,"-0,77","0,29","8,96","0,042","0,99304","8,9",0.47,"10,3",B,2,?,1.0,"3,79"
6362,13580,0,0,"0,41","0,07","8,88","0,587","0,9962","4,8",3.72,"7,6",M,3,?,2.0,"2,15"
6363,10080,0,0,"-0,2","0,38","8,19","0,052","1,00796","13,6",0.44,"13,8",B,2,*,1.0,"2,44"
6364,216,0,0,"0,22","-0,6","8,22","0,316","0,99834","9,1",1.79,"9,5",R,2,*,1.0,"6,18"

In [6]:
#compruebo de nuevo los nulos
#ver nulos del nuevo dataframe

df2.isnull().sum()

ID                0
Beneficio         0
Compra            0
Acidez            0
AcidoCitrico      0
pH                0
CloruroSodico     0
Densidad          0
Azucar            0
Sulfatos          0
Alcohol           0
Etiqueta          0
CalifProductor    0
Clasificacion     0
Region            0
PrecioBotella     0
dtype: int64

In [7]:
#compruebo los valores de la columna target
valores_unicos_compra = df2['Compra'].unique()
valores_unicos_compra

array([0, 1])

In [8]:
#recategorizaciÃ³n
#compruebo los valores unicos de la clasificacion ya que parecen ser simbolos y si decido utilizarlos es mejor sustituir por su equivalente en nÃºmeros

valores_unicos_clasificacion = df2['Clasificacion'].unique()
valores_unicos_clasificacion

array(['?', '*', '**', '***', '****'], dtype=object)

In [9]:
#utilizo mapping

mapping = {'?': 0, '*': 1, '**': 2, '***': 3, '****': 4}
df2['Clasificacion_int'] = df2['Clasificacion']
df2['Clasificacion_int'] = df2['Clasificacion_int'].replace(mapping)
df2

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella,Clasificacion_int
0,13606,0,0,"0,39","0,14","4,99","0,073","1,02195","5,9",0.12,"6,6",B,5,?,1.0,"4,56",0
1,3119,0,0,"2,19","2,58","5,54","0,205","0,95373","6,4",0.49,112,b,4,?,0.0,"3,01",0
2,1190,0,0,"1,44","-1,54","5,1","0,058","0,99271","7,1",0.39,"10,2",B,2,?,1.0,1,0
3,5261,0,0,"0,5","0,3","5,23","0,276","0,9959","3,5",-0.81,"4,4",R,4,?,3.0,"1,85",0
4,2871,0,0,"-0,1","0,3","5,75","0,048","1,02724","7,2",0.44,"10,1",M,2,?,1.0,"1,28",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,"0,41","0,17","8,55","-0,079","0,96961","9,5",0.45,"12,7",M,2,*,3.0,"1,55",1
6361,4285,0,0,"-0,77","0,29","8,96","0,042","0,99304","8,9",0.47,"10,3",B,2,?,1.0,"3,79",0
6362,13580,0,0,"0,41","0,07","8,88","0,587","0,9962","4,8",3.72,"7,6",M,3,?,2.0,"2,15",0
6363,10080,0,0,"-0,2","0,38","8,19","0,052","1,00796","13,6",0.44,"13,8",B,2,*,1.0,"2,44",1
6364,216,0,0,"0,22","-0,6","8,22","0,316","0,99834","9,1",1.79,"9,5",R,2,*,1.0,"6,18",1

In [10]:
#respecto a las etiquetas, son siglas de vino blanco, rosado etc
#compruebo valores unicos

valores_unicos_etiqueta = df2['Etiqueta'].unique()
valores_unicos_etiqueta

array(['B', 'b', 'R', 'M', 'r', 'MB', 'MM', 'mb', 'm', 'mm'], dtype=object)

In [11]:
#asigno valor numÃ©rico a cada tipo de vino en una nueva columna

mapping = {'B': 1, 'b': 2, 'R': 3, 'M': 4, 'r': 5, 'MB':6, 'MM':7, 'mb':8, 'm':9, 'mm':10 }
df2['Etiqueta_int'] = df2['Etiqueta']
df2['Etiqueta_int'] = df2['Etiqueta_int'].replace(mapping)
df2

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella,Clasificacion_int,Etiqueta_int
0,13606,0,0,"0,39","0,14","4,99","0,073","1,02195","5,9",0.12,"6,6",B,5,?,1.0,"4,56",0,1
1,3119,0,0,"2,19","2,58","5,54","0,205","0,95373","6,4",0.49,112,b,4,?,0.0,"3,01",0,2
2,1190,0,0,"1,44","-1,54","5,1","0,058","0,99271","7,1",0.39,"10,2",B,2,?,1.0,1,0,1
3,5261,0,0,"0,5","0,3","5,23","0,276","0,9959","3,5",-0.81,"4,4",R,4,?,3.0,"1,85",0,3
4,2871,0,0,"-0,1","0,3","5,75","0,048","1,02724","7,2",0.44,"10,1",M,2,?,1.0,"1,28",0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,"0,41","0,17","8,55","-0,079","0,96961","9,5",0.45,"12,7",M,2,*,3.0,"1,55",1,4
6361,4285,0,0,"-0,77","0,29","8,96","0,042","0,99304","8,9",0.47,"10,3",B,2,?,1.0,"3,79",0,1
6362,13580,0,0,"0,41","0,07","8,88","0,587","0,9962","4,8",3.72,"7,6",M,3,?,2.0,"2,15",0,4
6363,10080,0,0,"-0,2","0,38","8,19","0,052","1,00796","13,6",0.44,"13,8",B,2,*,1.0,"2,44",1,1
6364,216,0,0,"0,22","-0,6","8,22","0,316","0,99834","9,1",1.79,"9,5",R,2,*,1.0,"6,18",1,3

In [12]:
#el precio de las botellas estÃ¡ como tipo objeto y puede ser relevante cambio a numÃ©rico, al igual que el azucar,el ph....

columnas_num = ['Azucar','Densidad','pH','AcidoCitrico', 'Acidez','PrecioBotella','CloruroSodico']
df2[columnas_num] = df2[columnas_num].applymap(lambda x: float(x.replace(',', '.')))
df2

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella,Clasificacion_int,Etiqueta_int
0,13606,0,0,0.39,0.14,4.99,0.073,1.02195,5.9,0.12,"6,6",B,5,?,1.0,4.56,0,1
1,3119,0,0,2.19,2.58,5.54,0.205,0.95373,6.4,0.49,112,b,4,?,0.0,3.01,0,2
2,1190,0,0,1.44,-1.54,5.10,0.058,0.99271,7.1,0.39,"10,2",B,2,?,1.0,1.00,0,1
3,5261,0,0,0.50,0.30,5.23,0.276,0.99590,3.5,-0.81,"4,4",R,4,?,3.0,1.85,0,3
4,2871,0,0,-0.10,0.30,5.75,0.048,1.02724,7.2,0.44,"10,1",M,2,?,1.0,1.28,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,0.41,0.17,8.55,-0.079,0.96961,9.5,0.45,"12,7",M,2,*,3.0,1.55,1,4
6361,4285,0,0,-0.77,0.29,8.96,0.042,0.99304,8.9,0.47,"10,3",B,2,?,1.0,3.79,0,1
6362,13580,0,0,0.41,0.07,8.88,0.587,0.99620,4.8,3.72,"7,6",M,3,?,2.0,2.15,0,4
6363,10080,0,0,-0.20,0.38,8.19,0.052,1.00796,13.6,0.44,"13,8",B,2,*,1.0,2.44,1,1
6364,216,0,0,0.22,-0.60,8.22,0.316,0.99834,9.1,1.79,"9,5",R,2,*,1.0,6.18,1,3

In [13]:
#hay columnas de tipo objeto que ademÃ¡s se refieren a porcentajes, modifico
#aplico la transformaciÃ³n a las columnas seleccionadas

porcentaje = ['Alcohol']
df2[porcentaje] = df2[porcentaje].applymap(lambda x: float(x.replace(',', '.')) * 100)
df2

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella,Clasificacion_int,Etiqueta_int
0,13606,0,0,0.39,0.14,4.99,0.073,1.02195,5.9,0.12,660.0,B,5,?,1.0,4.56,0,1
1,3119,0,0,2.19,2.58,5.54,0.205,0.95373,6.4,0.49,11200.0,b,4,?,0.0,3.01,0,2
2,1190,0,0,1.44,-1.54,5.10,0.058,0.99271,7.1,0.39,1020.0,B,2,?,1.0,1.00,0,1
3,5261,0,0,0.50,0.30,5.23,0.276,0.99590,3.5,-0.81,440.0,R,4,?,3.0,1.85,0,3
4,2871,0,0,-0.10,0.30,5.75,0.048,1.02724,7.2,0.44,1010.0,M,2,?,1.0,1.28,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,0.41,0.17,8.55,-0.079,0.96961,9.5,0.45,1270.0,M,2,*,3.0,1.55,1,4
6361,4285,0,0,-0.77,0.29,8.96,0.042,0.99304,8.9,0.47,1030.0,B,2,?,1.0,3.79,0,1
6362,13580,0,0,0.41,0.07,8.88,0.587,0.99620,4.8,3.72,760.0,M,3,?,2.0,2.15,0,4
6363,10080,0,0,-0.20,0.38,8.19,0.052,1.00796,13.6,0.44,1380.0,B,2,*,1.0,2.44,1,1
6364,216,0,0,0.22,-0.60,8.22,0.316,0.99834,9.1,1.79,950.0,R,2,*,1.0,6.18,1,3

In [21]:
#procedo con la anulacion de valores negativos. 
#segÃºn la informaciÃ³n de la quÃ­mica del vino no puede haber resultados negativos en la acidez, acido citrico, ph, cloruro, sulfatos

replace = ['Acidez', 'AcidoCitrico', 'pH', 'CloruroSodico', 'Densidad', 'Azucar', 'Sulfatos']

df2[replace] = df2[replace].applymap(lambda x: 0 if x < 0 else x)
df2

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella,Clasificacion_int,Etiqueta_int
0,13606,0,0,0.39,0.14,4.99,0.073,1.02195,5.9,0.12,660.0,B,5,?,1.0,4.56,0,1
1,3119,0,0,2.19,2.58,5.54,0.205,0.95373,6.4,0.49,11200.0,b,4,?,0.0,3.01,0,2
2,1190,0,0,1.44,0.00,5.10,0.058,0.99271,7.1,0.39,1020.0,B,2,?,1.0,1.00,0,1
3,5261,0,0,0.50,0.30,5.23,0.276,0.99590,3.5,0.00,440.0,R,4,?,3.0,1.85,0,3
4,2871,0,0,0.00,0.30,5.75,0.048,1.02724,7.2,0.44,1010.0,M,2,?,1.0,1.28,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,0.41,0.17,8.55,0.000,0.96961,9.5,0.45,1270.0,M,2,*,3.0,1.55,1,4
6361,4285,0,0,0.00,0.29,8.96,0.042,0.99304,8.9,0.47,1030.0,B,2,?,1.0,3.79,0,1
6362,13580,0,0,0.41,0.07,8.88,0.587,0.99620,4.8,3.72,760.0,M,3,?,2.0,2.15,0,4
6363,10080,0,0,0.00,0.38,8.19,0.052,1.00796,13.6,0.44,1380.0,B,2,*,1.0,2.44,1,1
6364,216,0,0,0.22,0.00,8.22,0.316,0.99834,9.1,1.79,950.0,R,2,*,1.0,6.18,1,3

In [27]:
categorias = {'Compra':'category',
              'Etiqueta':'category',
              'Clasificacion_int':'category',
             'Etiqueta_int':'category'}
df2= df2.astype(categorias)
df2

,ID,Beneficio,Compra,Acidez,AcidoCitrico,pH,CloruroSodico,Densidad,Azucar,Sulfatos,Alcohol,Etiqueta,CalifProductor,Clasificacion,Region,PrecioBotella,Clasificacion_int,Etiqueta_int
0,13606,0,0,0.39,0.14,4.99,0.073,1.02195,5.9,0.12,660.0,B,5,?,1.0,4.56,0,1
1,3119,0,0,2.19,2.58,5.54,0.205,0.95373,6.4,0.49,11200.0,b,4,?,0.0,3.01,0,2
2,1190,0,0,1.44,0.00,5.10,0.058,0.99271,7.1,0.39,1020.0,B,2,?,1.0,1.00,0,1
3,5261,0,0,0.50,0.30,5.23,0.276,0.99590,3.5,0.00,440.0,R,4,?,3.0,1.85,0,3
4,2871,0,0,0.00,0.30,5.75,0.048,1.02724,7.2,0.44,1010.0,M,2,?,1.0,1.28,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6360,15918,0,0,0.41,0.17,8.55,0.000,0.96961,9.5,0.45,1270.0,M,2,*,3.0,1.55,1,4
6361,4285,0,0,0.00,0.29,8.96,0.042,0.99304,8.9,0.47,1030.0,B,2,?,1.0,3.79,0,1
6362,13580,0,0,0.41,0.07,8.88,0.587,0.99620,4.8,3.72,760.0,M,3,?,2.0,2.15,0,4
6363,10080,0,0,0.00,0.38,8.19,0.052,1.00796,13.6,0.44,1380.0,B,2,*,1.0,2.44,1,1
6364,216,0,0,0.22,0.00,8.22,0.316,0.99834,9.1,1.79,950.0,R,2,*,1.0,6.18,1,3

In [28]:
import pandas as pd
import seaborn as sns
from scipy.stats import chi2_contingency

# Seleccionar las variables categÃ³ricas de interÃ©s
variables_categoricas = ['Etiqueta', 'Clasificacion_int', 'Compra','Etiqueta_int']

# Crear una subconjunto del dataframe con las variables categÃ³ricas
df2_categorico = df2[variables_categoricas]

# Calcular la matriz de contingencia
matriz_contingencia = pd.crosstab(df2_categorico['Compra'], df2_categorico['Etiqueta_int'])

# Realizar la prueba de chi-cuadrado
chi2, p, dof, expected = chi2_contingency(matriz_contingencia)

# Imprimir los resultados
print("EstadÃ­stico chi-cuadrado:", chi2)
print("Valor p:", p)
print("Grados de libertad:", dof)
print("Valores esperados:")
print(expected)

EstadÃ­stico chi-cuadrado: 15.451444457198793
Valor p: 0.07925880891397671
Grados de libertad: 9
Valores esperados:
[[ 275.33291438   44.88656716  511.14846819  291.44053417   90.20267086
    41.02073841   46.38994501    8.59073056   49.39670071    8.59073056]
 [1006.66708562  164.11343284 1868.85153181 1065.55946583  329.79732914
   149.97926159  169.61005499   31.40926944  180.60329929   31.40926944]]

In [ ]:
#elimino la columna id
df2.drop('ID', axis=1, inplace=True)

In [ ]:
#obtengo los datos de las variables numÃ©ricas
df2.describe()

In [ ]:
#por curiosidad compruebo que tipo de vino aparece mÃ¡s, siendo el Rosado

import seaborn as sns
import matplotlib.pyplot as plt

# Crear un DataFrame solo con las columnas "Etiqueta" y "Compra"
df2_etiqueta_compra = df2[['Etiqueta_int', 'Compra']]

# Contar las ocurrencias de cada etiqueta segÃºn el valor de compra
conteo_etiqueta_compra = df2_etiqueta_compra.groupby(['Etiqueta_int', 'Compra']).size().unstack()

# Crear el grÃ¡fico de barras apiladas
conteo_etiqueta_compra.plot(kind='bar', stacked=True)

# Personalizar el grÃ¡fico
plt.xlabel('Etiqueta')
plt.ylabel('Cantidad')
plt.title('DistribuciÃ³n de Etiquetas segÃºn Compra')
plt.legend(title='Compra')

# Mostrar el grÃ¡fico
plt.show()

In [ ]:
#procedo con la comprobaciÃ³n de correlaciÃ³n de variables
correlation_matrix = df2.corr()
print(correlation_matrix)

In [ ]:
#import seaborn as sns

# Calcula la matriz de correlaciÃ³n
correlation_matrix = df2.corr()

# Visualiza la matriz de correlaciÃ³n como un mapa de calor
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Matriz de correlaciÃ³n')
plt.show()

In [ ]:
df2.corr()[['Compra']].sort_values(by='Compra', ascending = False)

La correlaciÃ³n entre "Beneficio" y "Compra" es de 0.767250, lo que indica una correlaciÃ³n positiva fuerte. Esto significa que a medida que aumenta el beneficio, es mÃ¡s probable que se realice una compra.

In [ ]:
#comprobacion de las correlaciones mas altas
correlaciones_df = df2[['Compra', 'Beneficio', 'Clasificacion_int', 'Azucar']]

# Calcular la matriz de correlaciÃ³n
correlation_matrix = correlaciones_df.corr()

# Crear el grÃ¡fico de correlaciÃ³n
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("CorrelaciÃ³n entre variables")
plt.show()

Podemos observar que las variables que tienen mÃ¡s correlaciÃ³n con 'Compra', tambiÃ©n la tienen con 'Beneficio', que es la variable que tiene correlaciÃ³n mÃ¡s alta

In [ ]:
#compruebo de otra manera la relaciÃ³n entre Clasificacion y Compra ya que son variables categoricas
from scipy.stats import chi2_contingency

# Crear una tabla de contingencia entre las variables "Clasificacion_int" y "Compra"
tabla_contingencia = pd.crosstab(df2['Clasificacion_int'], df2['Compra'])

# Aplicar el test de chi-cuadrado
chi2, p_value, dof, expected = chi2_contingency(tabla_contingencia)

# Imprimir los resultados
print("EstadÃ­stico chi-cuadrado:", chi2)
print("Valor p:", p_value)
print("Grados de libertad:", dof)
print("Valores esperados:", expected)

El resultado indica que hay una asociaciÃ³n estadÃ­sticamente significativa entre las variables "Clasificacion_int" y "Compra", lo que sugiere que la variable "etiqueta" puede ser un predictor importante para la variable "compra".

In [ ]:
#comprobacion del modelo

from sklearn.model_selection import train_test_split,cross_val_score, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# DivisiÃ³n de los datos en conjunto de entrenamiento y prueba
X = df2[['Beneficio', 'Clasificacion_int', 'Azucar']]  # Variables predictoras
y = df2['Compra']  # Variable objetivo

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# CreaciÃ³n y ajuste del modelo de regresiÃ³n logÃ­stica
model = LogisticRegression()
model.fit(X_train, y_train)

# PredicciÃ³n en el conjunto de prueba
y_pred = model.predict(X_test)

# EvaluaciÃ³n del modelo
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("PrecisiÃ³n:", precision)
print("Recall:", recall)
print("Puntaje F1:", f1)

In [ ]:
X = df2[['Azucar', 'Clasificacion_int']]
y = df2['Compra']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

In [ ]:

# Definir los datos de entrada (X) y la variable objetivo (y)
X = df2[['Beneficio', 'Clasificacion_int']]
y = df2['Compra']

# Definir el modelo de regresiÃ³n logÃ­stica
model = LogisticRegression()

# Definir el nÃºmero de divisiones (k) para la validaciÃ³n cruzada
k = 5

# Definir el esquema de validaciÃ³n cruzada
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Realizar la validaciÃ³n cruzada y obtener los puntajes de precisiÃ³n
scores = cross_val_score(model, X, y, scoring='accuracy', cv=kf)

# Imprimir los puntajes de precisiÃ³n obtenidos en cada iteraciÃ³n
print("Puntajes de precisiÃ³n:", scores)

# Calcular la precisiÃ³n promedio y desviaciÃ³n estÃ¡ndar de los puntajes
mean_accuracy = scores.mean()
std_accuracy = scores.std()

# Imprimir la precisiÃ³n promedio y desviaciÃ³n estÃ¡ndar
print("PrecisiÃ³n promedio:", mean_accuracy)
print("DesviaciÃ³n estÃ¡ndar:", std_accuracy)

Los resultados obtenidos con la regresiÃ³n logÃ­stica muestran una alta precisiÃ³n y puntajes perfectos en las mÃ©tricas de precisiÃ³n, recall y F1-score para diferentes combinaciones de variables.

En el primer caso, al usar las variables 'Beneficio', 'Clasificacion_int' y 'Azucar', se obtiene un puntaje perfecto de 1.0 en todas las mÃ©tricas. Esto indica que el modelo de regresiÃ³n logÃ­stica pudo ajustarse perfectamente a los datos y realizar predicciones precisas en el conjunto de prueba.

En el segundo caso, al usar las variables 'Azucar' y 'Clasificacion_int', se obtiene una precisiÃ³n de aproximadamente 0.86, lo cual sigue siendo bastante alto. La precisiÃ³n representa la proporciÃ³n de predicciones correctas en relaciÃ³n con el total de predicciones realizadas. AdemÃ¡s, hay valores altos en las mÃ©tricas de recall (0.92) y F1-score (0.91), lo que indica un buen equilibrio entre la precisiÃ³n y la capacidad del modelo para capturar los casos positivos.

En el Ãºltimo caso, con la validaciÃ³n cruzada con las variables 'Beneficio' y 'Clasificacion_int' obtuve puntajes de precisiÃ³n perfectos (1.0) en todas las iteraciones. Esto indica que el modelo es capaz de generalizar bien y tener un rendimiento consistente en diferentes subconjuntos de datos.

En general, los resultados muestran que las variables 'Beneficio', 'Clasificacion_int' y 'Azucar' tienen una fuerte relaciÃ³n con la variable objetivo 'Compra', y el modelo de regresiÃ³n logÃ­stica puede capturar esta relaciÃ³n y realizar predicciones precisas. Sin embargo, sigo teniendo dudas sobre que este anÃ¡lisis sea correcto.